webtalk_init -webtalk_dir C:/Users/lgehu/Documents/Polytech Dijon/SOC/ctrl_sram/ctrl_sram.sim/sim_1/behav/xsim/xsim.dir/tristate_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Dec 15 18:47:09 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "213656518_0_0_762" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c1393e71-ff65-477f-b21c-af90ec4cf81a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "26c7be3575a54fff9e26ad4dbfc5d78c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "21" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i7-13620H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2918 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8408_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2682444013 -regid "213656518_0_0_762" -xml C:/Users/lgehu/Documents/Polytech Dijon/SOC/ctrl_sram/ctrl_sram.sim/sim_1/behav/xsim/xsim.dir/tristate_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/lgehu/Documents/Polytech Dijon/SOC/ctrl_sram/ctrl_sram.sim/sim_1/behav/xsim/xsim.dir/tristate_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/lgehu/Documents/Polytech Dijon/SOC/ctrl_sram/ctrl_sram.sim/sim_1/behav/xsim/xsim.dir/tristate_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
